# Generated by Django 4.0.3 on 2022-05-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocksy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=50)),
            ],
        ),
    ]
