# Generated by Django 4.0.3 on 2022-05-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_stocksy_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksy',
            name='fair_value',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
    ]
